[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "npm install --include=dev",
  "cd backend && npm install --include=dev",
  "cd frontend && npm install --include=dev"
]

[phases.build]
cmds = [
  "cd backend && npx prisma generate && npx nest build",
  "cd frontend && npm run build"
]

[start]
cmd = "cd backend && npx ts-node prisma/seed-super-admin.ts && cd .. && npm run start"
